title: Jennie Tram Le
logo: "Jennie Le.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Possess 2 years of experience in analytics at economic consulting firm and scocial start-up. Currently pursuing a master degree in Business Analytics from Gabelli School of Business, Fordham University. Passionate about big data, machine learning, and data visualization. Experience in Python, R, Tableau and SQL.   
  <br><br>
  I love to create beautiful charts that can convey meaningful stories and bring values to businesses and the public. As a hard core fan of Rap, I am also eagerly studying about recommendation system, especially in music industry. I am a puppy-lover with island fetish. I enjoy cooking, motorbike-riding, and playing piano. My favourite classical pieces are Canon in D and Moonlight.     
  <br><br>
  <a href="https://www.linkedin.com/in/jennie-tram-le-6543b8b6/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
